image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

stages:
  - Static Analysis
  - Unit Test
  - Documentation

flake8:
  stage: Static Analysis
  #allow_failure: true
  script:
  - python3 -m flake8 gunc/*.py
  except:
    - docs

unit_test:
  stage: Unit Test
  script:
  - python -m pytest
  except:
    - docs

coverage:
  stage: Unit Test
  script:
    - coverage run -m pytest
    - coverage report -m
    - coverage xml -o coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week
  except:
    - docs

pages:
  stage: Documentation
  script:
    - python3 -m pip install .
    - make -C docs html
    - mkdir public
    - mv docs/build/html/* ./public
  artifacts:
    paths:
    - public
    expire_in: 1 week
  only:
    - docs
